VERSION := 0.1.7
OS ?= $(shell uname -s)
#ASAN ?= -g -fsanitize=address
CXXFLAGS += -std=c++11 $(ASAN)
CXXWARNFLAGS := -Wall -Wold-style-cast -Wundef -Wsign-compare -Wconversion -Wpointer-arith -pedantic
CXXFLAGS += $(CXXWARNFLAGS) -g3 -Og -fPIC
LDFLAGS += $(ASAN)

ifeq ($(OS), Windows)
WINE ?= wine

endif

prefix := /usr
