VERSION := 0.1.7
OS ?= $(shell uname -s)
CXXFLAGS += -std=c++11
CXXWARNFLAGS := -Wall -Wold-style-cast -Wundef -Wsign-compare -Wconversion -Wpointer-arith -pedantic
CXXFLAGS += $(CXXWARNFLAGS) -g3 -Og

ifeq ($(OS), Windows)
WINE ?= wine

endif

prefix := /usr
